fyrn:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: fyrn
    username: root
    password: root

  redis:
    host: 127.0.0.1
    port: 6379
    password: root

  minio:
    access-key-id: eZkIBk8WaWlfxjCx5OAW
    access-key-secret: 5smkTin7spqzPpfHH82UphdBS2YBhr1W3f1muzUT
    bucket-name: fyrn
    endpoint: http://localhost:9000

  logging:
    level: info

  mybatis:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
