server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
    banner-mode: off
  datasource:
    driver-class-name: ${fyrn.datasource.driver-class-name}
    url: jdbc:mysql://${fyrn.datasource.host}:${fyrn.datasource.port}/${fyrn.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${fyrn.datasource.username}
    password: ${fyrn.datasource.password}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  data:
    redis:
      host: ${fyrn.redis.host}
      port: ${fyrn.redis.port}
      password: ${fyrn.redis.password}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false

minio:
  access-key-id: ${fyrn.minio.access-key-id}
  access-key-secret: ${fyrn.minio.access-key-secret}
  bucket-name: ${fyrn.minio.bucket-name}
  endpoint: ${fyrn.minio.endpoint}