version: '3.8'
services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "59000:9000"
      - "59001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 123456
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - fyrn-network

  mariadb:
    image: mariadb:10.11
    container_name: my_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "53306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - fyrn-network

  redis:
    image: redis:7-alpine
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "56379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --requirepass root --appendonly yes
    environment:
      - REDIS_PASSWORD=123456
    networks:
      - fyrn-network

networks:
  fyrn-network:
    driver: bridge
