version: "3.8"
services:
  fyrn-backend:
    build: .
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./config/application-prod.yml:/app/config/application-prod.yml
    environment:
      - TZ=Asia/Shanghai
